### ISSUE TITLE
Format de fichier ALTO ou Page ?

### ISSUE THREAD

**Issue by baudbaudy** [kat-kel/TNAH-2021-Expositions_Universelles#10]
Afin que nous soyons tous d'accord, quel format de fichier avez-vous pris?

**Comment by paulhectork** [comment]
moi j'ai pris PAGE mais on dirait que la préférence est pour ALTO ? si c'est le cas je peux tout reexporter dans l'autre format

**Comment by kat-kel** [comment]
Le format ALTO ne permet pas de rajouter des balises au texte, parce que le texte est encodé comme le valeur d'un attribut d'un élément. Dans le format PAGE, par contre, le texte est balisé d'un élément, spécifiquement l'élément `<Unicode>`.

Si on choisissait le format ALTO, on n'aurait pas besoin de rajouter des balises pour l'italique, etc. puisque on n'aurait pu. De plus, je crois que le format ALTO est préféré parce qu'il permet de mieux aligner l'encodage avec l'image, ce qu'on ne va pas faire dans le cadre de ce projet mais qui est généralement souhaité.

(D'ailleurs je viens de pusher les xml PAGE et ALTO vers ma branche.)

**Comment by paulhectork** [comment]
en format PAGE, si on met une balise dans l'élément `<Unicode/>`, on reçoit un message d'erreur : 
```xml
L'élément Unicode est un type simple, il ne doit donc pas avoir d'article d'informations d'éléments [children]
```
donc, si on traduit : impossible de mettre de l'italique ou des balises de style, ni dans PAGE, ni dans ALTO. ce qui nous ramène à la graaande question : **quel format utilise-t-on ?**

**Comment by baudbaudy** [comment]
Kelly avait dit que monsieur Clérice préférait le format Alto

**Comment by baudbaudy** [comment]
Par ailleurs, que pensez-vous de rajouter, en plus des transcriptions xml de nos textes, les fichiers png que l'on peut avoir de ces derniers avec l'option "include image" de escriptorium?

**Comment by paulhectork** [comment]
de mon côté c'est fait ; j'ai aussi fait correspondre les noms des fichiers png avec les noms des documents XML produits ; si on renomme les png, alors il faut aussi modifier le XML l'élément `<sourceImageInformation/>` pour qu'il colle avec le nom du png ; par exemple, dans mon cas: 
```xml
<sourceImageInformation>
   <fileName>PAUL_Des-differences_p274.png</fileName>
</sourceImageInformation>
```
(oui c'est une petite complexité supplémentaire fort amusante)

**Comment by Oeconomo** [comment]
Bonjour à tous ! Je retiens donc de faire mon export en Alto.

**Comment by anahihaedo** [comment]
On fait l'export du fichier ALTO avec les images, non?

**Comment by anahihaedo** [comment]
Bonjour, oui, le fichier Alto avec les images.
