### ISSUE TITLE
Caractères étrangères

### ISSUE THREAD

**Issue by kat-kel** [kat-kel/TNAH-2021-Expositions_Universelles#11]
Bonjour tout le monde,

Dans l'extrait que je transcris se trouvent beaucoup de langues étrangères. En utilisant l'internet, des dictionnaires numérisés, et un ami qui lit sanskrit, je me débrouille pour trouver l'unicode et les transcrire dans eScriptorium.

Mais il y a certains mots que je n'arrive pas à décoder. Peut-être vous pouvez m'aider. Je les ajouterai dans cette issue.

`« l’impératif अस्तु astu nous rappelle le grec ἔσ[?]ω et le latin esto »`

Je n'arrive pas à comprendre le mot en grec ici, surtout sa troisième lettre que je ne trouve pas dans l'alphabet ancien grec.

<img width="291" alt="Screen Shot 2022-01-13 at 12 19 13 PM" src="https://user-images.githubusercontent.com/63346582/149321059-3d38d3da-9df8-45d1-a920-d357dab8c64f.png">

**Comment by paulhectork** [comment]
c'est une ancienne manière d'écrire le τ (tau, t) qui date du XVIIIe XIXe siècle ! tu peux le remplaxer par le τ grec contemporain je dirais

**Comment by kat-kel** [comment]
Résolu ! Il est en persan et je l'ai transcrit comme ça : هست

2. Je ne reconnais pas l'alphabet ici. En supposant qu'il est de l'arabe, j'ai essayé de rechercher le mot avec la translitération française des auteurs, mais je ne l'ai pas trouvé.

<img width="859" alt="Screen Shot 2022-01-13 at 12 31 56 PM" src="https://user-images.githubusercontent.com/63346582/149322752-a495cf07-f922-47a3-beae-ac59b33aba30.png">

**Comment by kat-kel** [comment]
3. Afin d'encoder un mot en avestique (une langue anciennement appelée zend) j'ai consulté un article scientifique du chercheur Jost Gippert, de Goethe-Universität Frankfurt am Main. J'ai trouvé l'unicode pour les lettres grâce à lui, et je voudrais qu'on cite son article dans notre rapport.

Jost Gippert, « The Encoding of Avestan — Problems and Solutions», _Journal for Language Technology and Computational Linguistics_ 27, no. 2 (2012), 1-24.

D'ailleurs, je pense qu'on on avait la chance que les anthropologues au XIX n'a pas bien transcrit le mot en avestique. _Stâ_, qui veut dire se lever, se compose normalement d'une ligature qui combine le « s » et le « t ». Mais nos anthropologues l'a transcrit lettre par lettre et ils on évité la ligature, ce qui a rendu l'unicode plus simple à utiliser.

<img width="1264" alt="Screen Shot 2022-01-13 at 2 18 10 PM" src="https://user-images.githubusercontent.com/63346582/149339898-95e530e9-d7fa-416a-8dd3-59c53c7bd6ef.png">
<img width="1264" alt="Screen Shot 2022-01-13 at 2 34 16 PM" src="https://user-images.githubusercontent.com/63346582/149339926-196866c3-ff6b-4867-abe5-43b20646d3ed.png">

**Comment by paulhectork** [comment]
Bravo pour toutes ces recherches ! On citera Jost Gippert, bien sûr. Si jamais tu as d'autres problèmes avec le grec n'hésite pas ! Malheureusement, pour les autres langues je ne devrais pas être d'une grande aide

**Comment by kat-kel** [comment]
Dans mon extrait, j'ai trouvé les langues suivantes. Si tu connais l'une des langues et que tu penses que j'ai mal encodé l'un des mots, dis-moi. :) La plupart de temps, les auteurs ont évoqué ces mots sans contexte sémantique, en parlant de l'étymologie.

### Grec

> εἶναι , εἶναι , εἰμί , ἐών, ἐόντος, ὤν, ὄντος, ἐσσί, ἔστω

> εἰ-μί, ἐσ-μὶ, ἐ-ών, ἐ-όντος, γένεσ-ος, γἐνε-ος, γἐνονς

> τίρ --> τίς, νέχυρ --> νέχυς, ζούγωνερ --> ζούγωνες, ῶίσορ --> ῶίθος

> φόρμιγγος περικαλλέος, ἣν ἔχ᾽ Ἀπόλλων
> Μουσάων θ᾽, αἳ ἄειδον ἀμειβόμεναι ὀπὶ καλῇ

> οὐδὲ Μουσᾶν χοροί
> Nιν ἀπεστύγησαν, οὐδὲ y᾽
> Ἀ χρυσάνιος Ἀφροδίτα

### Ruse

> бЫТЬ, бЫТЬ, есмь, быль, буду


### Paléoslave

> ІЄСМЬ


### Sanscrit

> अस्मि, असि, अस्ति, स्मः, स्थ, शान्ति, भू, अस्तु, स्था


### Persan

 هست
| `U+FE96` | `U+FEB4` | `U+FEEB` |

### Avestique

𐬯𐬙𐬁
| `U+10B01` | `U+10B19` | `U+10B00` |

**Comment by paulhectork** [comment]
alors je connais que le grec et tout m'a l'air bon, sauf peut-être le `οὐδὲ y᾽` : pour la dernière lettre, tu as mis `y`, mais c'est peut-être `γ` ? (le y n'existe pas dans l'alphabet grec, à ce que je sache)

**Comment by paulhectork** [comment]
Il y a un nouveau problème qui émerge : c'est assez difficile **d'encoder les caractères non-latins avec latex** ; j'ai réussi à encoder le `tau` grec ; par contre, je n'ai pas réussi à indexer le farsi, même après avoir fait beaucoup de recherches et tentatives :^/

**Comment by paulhectork** [comment]
la transcription des caractères grecs et latins en latex étant enfin réussie, je me permet de fermer l'issue : ^ )
