### ISSUE TITLE
Bibliographie

### ISSUE THREAD

**Issue by Oeconomo** [kat-kel/TNAH-2021-Expositions_Universelles#14]
Bonsoir à tous et à toutes,

J'ai créé bibliographie.txt, puisque j'imagine qu'une partie conséquente de cette section correspond à la présentation du contexte historique et des enjeux scientifiques que je termine. Il serait peut-être bien que vous rajoutiez vos propres références, puis on mettra le tout dans le README.md.
Il y a deux possibilités : soit on fait une bibliographie générale, soit on la divise par thèmes. Vous préférez quoi ?

**Comment by paulhectork** [comment]
vu la taille de la bibliographie complète, je pense qu'une bibliographie générale restera le mieux, pas la peine de (trop) se couper les cheveux en quatre

**Comment by paulhectork** [comment]
S'il vous plaît à tous : envoyez vos références bibliographiques à Esteban pour qu'il puisse nous faire un beau fichier .bib pour le compte rendu !

**Comment by paulhectork** [comment]
est-ce que l'on rajoute le document et les articles qu'on a retranscrit à la bibliographie ?

**Comment by anahihaedo** [comment]
Ok, oui je pense qu'il doit être dans la bibliographie.

**Comment by paulhectork** [comment]
parfait ! Esteban s'en charge, je crois

**Comment by Oeconomo** [comment]
J'ai mis la bibliographie du rapport complet, je ne pense pas qu'il soit nécessaire de spécifier chaque article. Par contre, je pense que ce serait une bonne idée que chacun spécifie l'article ou les articles sélectionnés sur extraits.txt.

**Comment by anahihaedo** [comment]
Je suis d'accord avec Esteban. Ok pour spécifié dans les extraits.

**Comment by paulhectork** [comment]
la bibliographie est définitivement prête alors ! je ferme l'issue
