### ISSUE TITLE
Issue Labels

### ISSUE THREAD

**Issue by kat-kel** [kat-kel/TNAH-2021-Expositions_Universelles#4]
Bonjour à toutes et à tous,

Pour bien documenter notre travail collaboratif avec des "issues", on peut les marquer avec des labels. Par défaut il y en a neuf :
- bug
- documentation
- duplicate
- enhancement
- good first issue
- help wanted
- invalid
- question
- wontfix

Est-ce qu'on veut en ajouter quelques ?

**Comment by Oeconomo** [comment]
Bonjour Kelly, pour ma part je pense que ces labels nous suffisent, et qu'on n'aura même pas à tous les utiliser. Elles correspondent à des questions e communication, qui sont exactement ce dont on a besoin. Mais on peut les personaliser si toi et les autres pensent que c'est plus précis.

**Comment by paulhectork** [comment]
Bonjour à tous et toutes,
Pour le moment je pense que ces labels nous suffisent amplement et qu'ils couvrent n'importe quel type de problème que l'on pourrait rencontrer. Si jamais des problèmes non couverts émergent (ce que je n'espère pas!), on pourrait réactiver ce fil de conversation pour parler des nouveaux labels à ajouter. Qu'en pensez-vous ?
