### ISSUE TITLE
eScriptorium main script non latin

### ISSUE THREAD

**Issue by kat-kel** [kat-kel/TNAH-2021-Expositions_Universelles#5]
Bonjour à tous qui veulent transcrire un texte écrit dans un alphabet autre que latin,

Chaque document d'un projet d'eScriptorium a sa propre 'Description' qui déclare le 'main script' du document. Selon nos comptes d'eScriptorium fournis par l'école, on peut sélectionner peu importe quel script disponible dans le menu déroulant. Moi, par exemple, j'ai créé un nouveau document et j'ai sélectionné le script 'Egyptian hieroglyphs' afin de transcrire les hiéroglyphes dans certaines pages.

Nous avons accès également à sept modèles : 
- 19th century prints - HTRCatalogs Artlas
- Modèle manuscrit DAHN NFC
- Modèle Cremma Médiéval 1.0.0 Bicerin
- Modèle imprimé 16-18e Fra+Lat
- Modèle Manuscrit 19e Lectaurep
- ModeleHTRneide_PostDocLucien
- CremmaLab67-95.49

Pour transcrire l'image, il faut sélectionner l'un de ces modèles. Et bien que le 'main script' du document soit 'l'Egpytian hieroglyphs,' la transcription sortie du modèle '19th century prints - HTRCatalogs Artlas' est dans un script latin.

La transcription du document n'est pas faite dans le script déclaré du document. Je me demande si le problème est une question de modèle.

**Comment by kat-kel** [comment]
Réponse de M. Clérice :

Tous nos modèles sont entraînés sur des caractères Latins, donc ils ne pourront produire autre chose (peut-être de temps à autre du grec, pour Modèle 19th). Il faut donc transcrire de 0 les lignes problématiques dans ce genre de situation... Ou ne pas transcrire/.

Ou "translittérer": https://fr.wikipedia.org/wiki/Translitt%C3%A9ration_des_hi%C3%A9roglyphes

**Comment by Oeconomo** [comment]
Bonjour Kelly, merci pour ces informations ! On nous a dit que le modèle 19e siècle Artl@s (produit par Simon Gabay si je ne me trompe pa) est très efficace, c'est idéal pour notre imprimé fin XIX, dont la structure n'est pas exactement un catalogue d'exposition, mais s'y rapproche. Je pense qu'il faudra qu'on fasse attention a ne choisir des textes avec trop de lignes non latines qui seraient pas traité par le modèle, et qui nous occuperaient inutilement à transcrire.
