### ISSUE TITLE
Numéro de page

### ISSUE THREAD

**Issue by kat-kel** [kat-kel/TNAH-2021-Expositions_Universelles#7]
Bonsoir !
Je me demande s'il faut transcrire le numéro de page. Anahi, dans ton expérience, comment est-ce qu'on traite des numéros de page ?

**Comment by anahihaedo** [comment]
Bonjour Kelly,
Je pense qu'il faut conserver les numéros de pages. Car c'est une partie importante du document aussi.
Par exemple si après on voudra utiliser cette transcription pour faire une encodage en XML-TEI, on pourra associer le numéro de page avec le lien de l'image en eScriptorium avec la balise <pb n="" facs="lien de l'image" />

**Comment by anahihaedo** [comment]
`<pb n="" facs="lien de l'image"/>`

**Comment by paulhectork** [comment]
Salut à tous.tes. Du coup, de ce que je comprends, on met notre transcription sur un seul document XML et à chaque nouvelle page, on fait `<pb n="" facs="lien de l'image"/>`. C'est bien ça ?

**Comment by paulhectork** [comment]
Re-bonjour, je viens d'ouvrir le document XML créé par eScriptorium et celui-ci n'autorise pas d'élément `<pb>`. Par contre, le numéro de page se trouvant à chaque début de page (logiquement), l'information n'est pas perdue dans la retranscription. Du coup, est-ce qu'il faut vraiment trouver une autre manière de retranscrire le n° de page ?

**Comment by anahihaedo** [comment]
Bonjour Paul, il n'autorise pas la balise pb, car n'est pas un document en XML-TEI. Je pense qu'il faut juste conserver le numéro de page dans la transcription, rien de plus.

**Comment by paulhectork** [comment]
Oui, tu as totalement raison :^) J'avais écrit ça avant de tenter d'utiliser `<pb>` dans le document XML et de me farcir un message d'erreur. Autant garder le numéro de page de la transcription du coup, l'info sera là !

**Comment by kat-kel** [comment]
Je suis d'accord avec Anahi. D'ailleurs, est-ce qu'il faut conserver la clause « Droits reservés au Cnam et à ses partenaires » au bout de la page ?

**Comment by paulhectork** [comment]
Moi je l'ai gardée, oui

**Comment by baudbaudy** [comment]
je l'ai gardé aussi
