### ISSUE TITLE
Fusionner les retranscriptions d'un même article

### ISSUE THREAD

**Issue by paulhectork** [kat-kel/TNAH-2021-Expositions_Universelles#8]
Salut à tous.tes, et plus particulièrement à notre cher `Baudoin` ;^). 
Étant donné que Baudoin & moi retranscrivons un même texte (moi les 10 premières pages, Baudoin les 10 dernières), est-ce qu'il serait pertinent de fusionner nos retranscriptions respectives dans un seul et même document XML, pour conserver l'intégrité du document originel ? 
Si oui, de quelle manière distinguer nos deux parties ? Je pensais inclure nos retranscription dans un élément `<div xml:id='Paul'>` (pour moi) et `<div xml:id='Baudoin'>` (pour Baudoin. logiquement.).
Je vous laisse vous exprimer librement là dessus :)

**Comment by paulhectork** [comment]
Après avoir re-regardé la sortie XML générée par eScriptorium : cette sortie est assez restrictive et n'autorise qu'un élément `<Page>` par document XML ; on ne pourra donc pas fusionner nos documents, Baudoin, ou au moins pas de cette manière.

**Comment by Oeconomo** [comment]
Pour ma part, j'estime qu'il est intéressant de fusionner les documents et trouver une manière pertinente de le signaler en XML ; cela a un intérêt scientifique et pose un précédent qui pourra ainsi être exploré pour développer des consignes solides à intégrer dans la documentation.

**Comment by paulhectork** [comment]
Je suis d'accord, mais le modèle XML PAGE de escriptorium est assez restrictif, donc je ne suis pas sûr de comment faire ça

**Comment by baudbaudy** [comment]
Que ce soit PAGE ou ALTO, je n'ai pas trouvé comment faire

**Comment by paulhectork** [comment]
c'est parce que en fait on peut pas héhé
